name: "Backend Code Testing"
description: "Custom GitHub Action to execute backend code tests"
inputs:
  python_version:
    description: "The Python version to be used for the testing process"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    # Step 1: Configure Python environment
    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    # Step 2: Cache pipenv dependencies for faster installs
    - name: Cache pipenv dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pipenv
        key: pipenv-cache-${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          pipenv-cache-${{ runner.os }}-

    # Step 3: Install required packages
    - name: Install required packages
      run: |
        pip install pipenv==2024.0.3
        pipenv install
      shell: bash

    # Step 4: Execute tests
    - name: Execute tests
      run: |
        pipenv run test -v
      shell: bash
