name: Backend Continuous Integration

on:
  # This allows running on-demand
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      # This will only run on changes to the backend code
      - "starter/backend/**"

env:
  PYTHON_VERSION: 3.11
  FLAKE8_MAX_LINE_LENGTH: 120

jobs:
  lint_job:
    name: Backend Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run backend lint custom action
        uses: ./.github/actions/lintBE
        with:
          python_version: ${{ env.PYTHON_VERSION }}
          flake8_max_line_length: ${{ env.FLAKE8_MAX_LINE_LENGTH }}

  test_job:
    name: Backend Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run backend test custom action
        uses: ./.github/actions/testBE
        with:
          python_version: ${{ env.PYTHON_VERSION }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint_job
      - test_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pipenv
          key: pipenv-${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            pipenv-${{ runner.os }}-

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Build
        working-directory: starter/backend
        run: docker build -t backend-app:latest .
